#!/usr/bin/env python3
"""ATSC A/52:2018 E3.9-E3.12 data and E.3.5.5 derived rotations.

Uses the hash-pinned primary PDF; imports no reference decoder code.
"""
import importlib.util
import math
from pathlib import Path
import re
import struct
import sys

spec = importlib.util.spec_from_file_location('eac3_numeric', Path(__file__).with_name('generate-eac3-tables.py'))
base = importlib.util.module_from_spec(spec)
spec.loader.exec_module(base)
TARGET = base.ROOT / 'src/eac3_ecpl_tables.inc'


def tables():
    text = base.specification_text()
    section = text.split('Table E2.13 Default Enhanced Coupling Banding Structure')[-1].split('2.3.3.19')[0]
    rows = re.findall(r'^\s*(\d+)(?:\s+to\s+(\d+))?\s+([01])\s*$', section, re.M)
    pairs = [(k, int(v)) for a, b, v in rows for k in range(int(a), int(b or a)+1)]
    assert [k for k, v in pairs] == list(range(22))
    bands = [v for k, v in pairs]
    assert bands == [0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,1,1,0,1,1,1]
    section = text.split('Table E3.9 Sub-band Transform Start Coefficients: ecplsubbndtab[]')[-1].split('Table E3.10')[0]
    rows = re.findall(r'^\s*(\d+)\s+(\d+)\s*$', section, re.M)
    assert [int(k) for k, v in rows] == list(range(23))
    edges = [int(v) for k, v in rows]
    assert edges == [13,19,25,31,37,49,61,73,85,97,109,121,133,145,157,169,181,193,205,217,229,241,253]
    section = text.split('Table E3.10 Amplitudes: ecplampexptab[], ecplampmanttab[]')[-1].split('Table E3.11')[0]
    rows = re.findall(r'^\s*(\d+)\s+(\d+|-)\s+(0x[0-9a-f]+)\s*$', section, re.M)
    assert [int(k) for k, e, m in rows] == list(range(32))
    amp = [int(m, 16) / 32 * 2**(-int(e)) if e != '-' else 0.0 for k, e, m in rows]
    assert amp[0] == 1 and amp[-1] == 0 and all(a > b for a, b in zip(amp, amp[1:]))
    section = text.split('Table E3.11 Angles: ecplangletab[]')[-1].split('Table E3.12')[0]
    rows = re.findall(r'^\s*(\d+)\s+(-?\d+\.\d+)\s+(\d+)\s+(-?\d+\.\d+)\s*$', section, re.M)
    pairs = sorted([(int(k), float(v)) for k, v, j, w in rows] + [(int(j), float(w)) for k, v, j, w in rows])
    assert [k for k, v in pairs] == list(range(64))
    angles = [v for k, v in pairs]
    assert angles == [(k if k < 32 else k-64)/32 for k in range(64)]
    section = text.split('Table E3.12 Chaos Scaling: ecplchaostab[]')[-1].split('3.5.4')[0]
    rows = re.findall(r'^\s*(\d+)\s+(-?\d+\.\d+)\s*$', section, re.M)
    assert [int(k) for k, v in rows] == list(range(8))
    chaos = [float(v) for k, v in rows]
    assert chaos == [0,-.142857,-.285714,-.428571,-.571429,-.714286,-.857143,-1]
    reverse = [int(f'{n:09b}'[::-1], 2) for n in range(512)]
    rotations = [v for n in range(512) for v in (math.cos(math.pi*n/512), -math.sin(math.pi*n/512))]
    twiddle = []
    for k in range(256):
        c, s = math.cos(2*math.pi*k/512), -math.sin(2*math.pi*k/512)
        twiddle.extend((c,c,-s,s))
    projection = [math.cos(2*math.pi*(128+.5)/512*(k+.5)) for k in range(256)]
    return edges, amp, angles, chaos, reverse, rotations, twiddle, projection, bands


def render(edges, amp, angles, chaos, reverse, rotations, twiddle, projection, bands):
    output = '# ATSC A/52:2018 E3.9-E3.12 and E.3.5.5 derived transform constants.\n'
    output += '# Generated by tests/generate-eac3-ecpl-tables.py; see docs/eac3.md.\n'
    output += 'eac3_default_ecpl_bands:\n    .byte '+','.join(map(str,bands))+'\n'
    for name, values in [('eac3_ecpl_edges', edges), ('eac3_ecpl_rev512', reverse)]:
        output += '\n.p2align 1\n'+name+':\n'
        for i in range(0, len(values), 16):
            output += '    .short '+','.join(map(str, values[i:i+16]))+'\n'
    for name, values in [('eac3_ecpl_amp',amp), ('eac3_ecpl_angle',angles), ('eac3_ecpl_chaos',chaos),
                         ('eac3_ecpl_rotation',rotations), ('eac3_ecpl_twiddle',twiddle), ('eac3_ecpl_projection',projection)]:
        output += '\n.p2align 4\n'+name+':\n'
        for i in range(0, len(values), 4):
            output += '    .quad '+','.join('0x%016x' % struct.unpack('<Q', struct.pack('<d', v))[0] for v in values[i:i+4])+'\n'
    return output


if __name__ == '__main__':
    generated = render(*tables())
    if '--check' in sys.argv:
        if TARGET.read_text() != generated:
            raise SystemExit('src/eac3_ecpl_tables.inc is stale')
        print('Enhanced-coupling numeric tables match the pinned A/52 specification')
    else:
        TARGET.write_text(generated)
