#!/usr/bin/env python3
"""Generate numeric E-AC-3 tables from ATSC A/52:2018 Annex E.

Tables E2.10/E2.11/E2.12 (exponents and bands) and E3.14 (SPX attenuation).
Downloads the hash-pinned primary specification to tests/reference (ignored),
extracts numeric data with pdftotext, and checks the structure before emitting.
No reference decoder code or external runtime library is included.
"""
import hashlib
import struct
from pathlib import Path
import re
import subprocess
import sys
import urllib.request

ROOT = Path(__file__).resolve().parent.parent
URL = 'https://www.atsc.org/wp-content/uploads/2021/04/A52-2018.pdf'
SHA256 = '4580b631f5ac1aafdd31034f28d5fc9c29bce72a3d3f6367e3d9746906e0ffa1'
TARGET = ROOT / 'src/eac3_tables.inc'
DEFAULT_CPL = [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1]


def specification_text():
    pdf = ROOT / 'tests/reference/A52-2018.pdf'
    if not pdf.exists():
        pdf.parent.mkdir(parents=True, exist_ok=True)
        with urllib.request.urlopen(URL, timeout=60) as response:
            pdf.write_bytes(response.read())
    if hashlib.sha256(pdf.read_bytes()).hexdigest() != SHA256:
        raise SystemExit('A52-2018.pdf SHA-256 mismatch')
    return subprocess.check_output(['pdftotext', '-layout', str(pdf), '-']).decode()


def tables():
    text = specification_text()
    section = text.split('Table E2.10 Frame Exponent Strategy Combinations')[-1].split('2.3.2.16')[0]
    rows = re.findall(r'^\s*(\d+)\s+((?:D15|D25|D45|R)(?:\s+(?:D15|D25|D45|R)){5})\s*$', section, re.M)
    assert [int(k) for k, _ in rows] == list(range(32))
    lut = [[{'R': 0, 'D15': 1, 'D25': 2, 'D45': 3}[x] for x in r.split()] for _, r in rows]
    section = text.split('Table E2.12 Default Coupling Banding Structure')[-1].split('2.3.3.10')[0]
    bands = re.findall(r'^\s*(\d+)\s+([01])\s*$', section, re.M)
    bands = [int(v) for k, v in bands if 1 <= int(k) <= 17]
    assert [0] + bands[:17] == DEFAULT_CPL
    section = text.split('Table E2.11 Default Spectral Extension Banding Structure')[-1].split('2.3.3.9')[0]
    rows = re.findall(r'^\s*(\d+)\s+([01])\s*$', section, re.M)
    spx = [int(v) for k, v in rows if 0 <= int(k) <= 16][:17]
    assert spx == [0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,0,1], spx
    section = text.split('Table E3.14 Spectral Extension Attenuation Table: spxattentab[][]')[-1].split('3.6.4.2.4')[0]
    rows = re.findall(r'^\s*(\d+)\s+(0\.\d+)\s+(0\.\d+)\s+(0\.\d+)\s*$', section, re.M)
    assert [int(k) for k, *r in rows] == list(range(32))
    atten = [[float(x) for x in r] for k, *r in rows]
    return lut, DEFAULT_CPL, spx, atten


def render(lut, bands, spx, atten):
    return ('# Numeric ATSC A/52:2018 Annex E Tables E2.10, E2.11, E2.12, E3.14.\n'
            '# Generated by tests/generate-eac3-tables.py; see docs/eac3.md.\n'
            'eac3_frame_expstr:\n' + ''.join('    .byte ' + ', '.join(map(str, r)) + '\n' for r in lut) +
            'eac3_default_cpl_bands:\n    .byte ' + ','.join(map(str, bands)) + '\n' +
            'eac3_default_spx_bands:\n    .byte ' + ','.join(map(str, spx)) + '\n.p2align 2\neac3_spx_atten:\n' +
            ''.join('    .long '+','.join(hex(struct.unpack('<I',struct.pack('<f',x))[0]) for x in r)+'\n' for r in atten))


if __name__ == '__main__':
    generated = render(*tables())
    if '--check' in sys.argv:
        if TARGET.read_text() != generated:
            raise SystemExit('src/eac3_tables.inc is stale')
        print('E-AC-3 normative tables match the pinned A/52 specification')
    else:
        TARGET.write_text(generated)
