#!/usr/bin/env python3
"""Generate src/sbr_tables.inc for the HE-AAC spectral band replication decoder.

usage: python3 tests/generate-sbr-tables.py [--check]

Sources, fetched at pinned commits into tests/reference/ and checked against
tests/reference/sbr-reference-hashes.json:
- PacketVideo AAC decoder (Apache License 2.0): the ten SBR Huffman trees
  (envelope and noise levels and balances, time and frequency direction) and
  the start-frequency offsets of ISO/IEC 14496-3 table 4.82.
- JAADec (public domain dedication): the 640 QMF window coefficients of
  ISO/IEC 14496-3 table 4.A.89 and the 512-entry noise table V of table 4.A.88,
  written here as exact single-precision bit patterns.
No reference code is linked into either player.
"""
import hashlib
import json
from pathlib import Path
import re
import struct
import sys
import urllib.request

ROOT = Path(__file__).resolve().parent.parent
TESTS = ROOT / 'tests'
TARGET = ROOT / 'src' / 'sbr_tables.inc'
# Tree order used by src/aac_sbr.inc.
TREES = ['bookSbrEnvLevel10T', 'bookSbrEnvLevel10F', 'bookSbrEnvBalance10T', 'bookSbrEnvBalance10F',
         'bookSbrEnvLevel11T', 'bookSbrEnvLevel11F', 'bookSbrEnvBalance11T', 'bookSbrEnvBalance11F',
         'bookSbrNoiseLevel11T', 'bookSbrNoiseBalance11T']


def fetch():
    spec = json.loads((TESTS / 'reference' / 'sbr-reference-hashes.json').read_text())
    paths = {}
    for source in spec['sources']:
        directory = TESTS / 'reference' / source['directory']
        for name, digest in source['files'].items():
            path = directory / name
            path.parent.mkdir(parents=True, exist_ok=True)
            if not path.exists():
                url = source['url'].format(commit=source['commit'], file=name)
                with urllib.request.urlopen(url, timeout=60) as response:
                    path.write_bytes(response.read())
            if hashlib.sha256(path.read_bytes()).hexdigest() != digest:
                raise SystemExit(f'{path}: SHA-256 differs from {source["commit"]}')
            paths[name] = path
    return paths


def floats(text, name):
    body = text.split(name, 1)[1].split('};', 1)[0]
    return [float(v.rstrip('fF')) for v in re.findall(r'-?\d+(?:\.\d+)?(?:[eE][-+]?\d+)?[fF]', body)]


def bits(value):
    return '0x%08x' % struct.unpack('<I', struct.pack('<f', value))[0]


def generate():
    paths = fetch()
    lines = ['# Generated by tests/generate-sbr-tables.py; do not edit.',
             '# SBR Huffman trees and start-frequency offsets from the PacketVideo AAC decoder',
             '# (Apache License 2.0); QMF window and noise table V of ISO/IEC 14496-3 from',
             '# JAADec (public domain dedication). See THIRD_PARTY_NOTICES.', '']
    books = paths['sbr_code_book_envlevel.cpp'].read_text()
    offsets, nodes = [], []
    for name in TREES:
        body = re.search(r'\b' + name + r'\[(\d+)\]\[2\]\s*=\s*\{(.*?)\};', books, re.S)
        pairs = [int(v) for v in re.findall(r'-?\d+', re.sub(r'/\*.*?\*/', '', body.group(2), flags=re.S))]
        if len(pairs) != 2 * int(body.group(1)):
            raise SystemExit(f'{name}: {len(pairs)} values')
        offsets.append(len(nodes) // 2)
        nodes += pairs
    lines.append('# Per tree (ten): first node in sbr_huff_nodes. A node holds the next node')
    lines.append('# for bit 0 and bit 1; negative entries are leaves, value = entry + 64.')
    lines.append('sbr_huff_trees:')
    lines.append('    .short ' + ', '.join(map(str, offsets)))
    lines.append('sbr_huff_nodes:')
    for i in range(0, len(nodes), 16):
        lines.append('    .byte ' + ', '.join(str(v & 0xff) for v in nodes[i:i + 16]))
    start = paths['get_sbr_startfreq.cpp'].read_text()
    rows = re.search(r'v_offset\[7\]\[16\]\s*=\s*\{(.*?)\};', start, re.S).group(1)
    values = [int(v) for v in re.findall(r'-?\d+', rows)]
    if len(values) != 112:
        raise SystemExit('v_offset: wrong size')
    lines.append('# Start-frequency offsets: 16, 22.05, 24, 32, 44.1-64, 88.2-96 kHz and other rates.')
    lines.append('sbr_start_offsets:')
    for i in range(0, 112, 16):
        lines.append('    .byte ' + ', '.join(str(v & 0xff) for v in values[i:i + 16]))
    window = floats(paths['src/main/java/net/sourceforge/jaad/aac/sbr/FilterbankTable.java'].read_text(), 'qmf_c')
    if len(window) != 640 or window[0] != 0.0:
        raise SystemExit('QMF window: wrong size')
    lines.append('.p2align 4')
    lines.append('sbr_qmf_window:')
    for i in range(0, 640, 8):
        lines.append('    .long ' + ', '.join(bits(v) for v in window[i:i + 8]))
    noise = floats(paths['src/main/java/net/sourceforge/jaad/aac/sbr/NoiseTable.java'].read_text(), 'NOISE_TABLE')
    if len(noise) != 1024:
        raise SystemExit('noise table: wrong size')
    lines.append('sbr_noise_table:')
    for i in range(0, 1024, 8):
        lines.append('    .long ' + ', '.join(bits(v) for v in noise[i:i + 8]))
    return '\n'.join(lines) + '\n'


def main():
    text = generate()
    if '--check' in sys.argv[1:]:
        if TARGET.read_text() != text:
            raise SystemExit('src/sbr_tables.inc differs from the reference extraction')
        print('Verified SBR tables against the PacketVideo and JAADec references.')
    else:
        TARGET.write_text(text)
        print(f'Generated {TARGET}')


if __name__ == '__main__':
    main()
