#!/usr/bin/env python3
"""Generate src/wavpack_tables.inc for the WavPack decoder.

usage: python3 tests/generate-wavpack-tables.py [--check]

WavPack's 8-bit fractional exponent and logarithm tables follow from their
definitions: exp2[i] = round(256 * 2^(i/256)) - 256 and log2[i] =
round(256 * log2(1 + i/256)). tests/wavpack_model.py uses the same formulas,
and the decoding tests (including a sweep of every exp2 input through
FFmpeg's decoder) confirm them.
"""
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
import wavpack_model

TARGET = Path(__file__).resolve().parent.parent / 'src' / 'wavpack_tables.inc'


def generate():
    lines = ['# Generated by tests/generate-wavpack-tables.py; do not edit.',
             '# exp2[i] = round(256 * 2^(i/256)) - 256, log2[i] = round(256 * log2(1 + i/256)).', '']
    for label, values in (('wv_exp2_table', wavpack_model.EXP2), ('wv_log2_table', wavpack_model.LOG2)):
        lines.append(label + ':')
        for i in range(0, 256, 16):
            lines.append('    .byte ' + ', '.join(str(v) for v in values[i:i + 16]))
    return '\n'.join(lines) + '\n'


def main():
    text = generate()
    if '--check' in sys.argv[1:]:
        if TARGET.read_text() != text:
            raise SystemExit('src/wavpack_tables.inc differs from its formulas')
        print('Verified WavPack tables against their formulas.')
    else:
        TARGET.write_text(text)
        print(f'Generated {TARGET}')


if __name__ == '__main__':
    main()
