#!/usr/bin/env python3
"""Generate src/adpcm_tables.inc for G.711 and the IMA and Microsoft ADPCM
decoders.

usage: python3 tests/generate-adpcm-tables.py [--check]

The G.711 A-law and mu-law expansions follow from the decoding rules of
ITU-T G.711; the IMA step/index and Microsoft adaptation/coefficient tables
are the published ones (see tests/adpcm_model.py). tests/verify-wav-codecs.py
decodes FFmpeg-encoded and randomly written streams that use every table
entry and compares them with FFmpeg.
"""
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
import adpcm_model as model

TARGET = Path(__file__).resolve().parent.parent / 'src' / 'adpcm_tables.inc'


def rows(label, directive, values, per_line=16):
    lines = [label + ':']
    for i in range(0, len(values), per_line):
        lines.append(f'    {directive} ' + ', '.join(str(v) for v in values[i:i + per_line]))
    return lines


def generate():
    lines = ['# Generated by tests/generate-adpcm-tables.py; do not edit.',
             '# G.711 expansions (ITU-T G.711), IMA ADPCM steps and index changes (IMA, 1992),',
             '# Microsoft ADPCM adaptation and predictor coefficients (Microsoft, 1994).', '.p2align 2']
    lines += rows('g711_alaw', '.short', model.ALAW)
    lines += rows('g711_ulaw', '.short', model.ULAW)
    lines += rows('ima_steps', '.short', model.IMA_STEPS)
    lines += rows('ima_index', '.byte', model.IMA_INDEX)
    lines.append('.p2align 2')
    lines += rows('ms_adapt', '.long', model.MS_ADAPT)
    lines += rows('ms_coeff1', '.long', model.MS_COEFF1)
    lines += rows('ms_coeff2', '.long', model.MS_COEFF2)
    return '\n'.join(lines) + '\n'


def main():
    text = generate()
    if '--check' in sys.argv[1:]:
        if TARGET.read_text() != text:
            raise SystemExit('src/adpcm_tables.inc differs from its definitions')
        print('Verified G.711 and ADPCM tables.')
    else:
        TARGET.write_text(text)
        print(f'Generated {TARGET}')


if __name__ == '__main__':
    main()
