#!/usr/bin/env python3
"""Numeric AHT data from the hash-pinned ATSC A/52:2018 specification.

Annex E Tables E3.1/E3.2/E3.6 and E4.1-E4.7. No reference decoder code.
The generated include contains 956 six-dimensional signed 16-bit vectors,
allocation/bit-count maps, remapping constants, and derived Q23 cosines.
"""
import importlib.util
import math
from pathlib import Path
import re
import sys

spec=importlib.util.spec_from_file_location('eac3_numeric',Path(__file__).with_name('generate-eac3-tables.py'))
base=importlib.util.module_from_spec(spec);spec.loader.exec_module(base)
TARGET=base.ROOT/'src/eac3_aht_tables.inc'


def signed(value):
    n=int(value,16)
    return n-65536 if n>=32768 else n


def tables():
    text=base.specification_text()
    section=text.split('Table E3.1 High Efficiency Bit Allocation Pointers, hebaptab[]')[-1].split('Table E3.2')[0]
    rows=re.findall(r'^\s*(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s*$',section,re.M)
    assert len(rows)==32
    pairs=sorted([(int(a),int(b)) for a,b,c,d in rows]+[(int(c),int(d)) for a,b,c,d in rows])
    assert [k for k,v in pairs]==list(range(64))
    hebap=[v for k,v in pairs]
    assert all(0<=x<=19 for x in hebap)
    section=text.split('Table E3.2 Quantizer Type, Quantizer Level, and Mantissa Bits vs. hebap')[-1].split('3.4.4')[0]
    rows=re.findall(r'^\s*(\d+)\s+.+?\s+(\(\d+/6\)|\d+)\s*$',section,re.M)
    assert [int(k) for k,v in rows]==list(range(20))
    bits=[int(re.search(r'\d+',v)[0]) for k,v in rows]
    assert bits==[0,2,3,4,5,7,8,9,3,4,5,6,7,8,9,10,11,12,14,16]
    vectors=[]
    for bap in range(1,8):
        section=text.split(f'Table E4.{bap} VQ Table for hebap {bap} (16-bit two’s complement)')[-1]
        if bap<7:section=section.split(f'Table E4.{bap+1}')[0]
        rows=re.findall(r'^\s*(\d+)\s+((?:0x[0-9a-fA-F]{4}\s+){5}0x[0-9a-fA-F]{4})\s*$',section,re.M)
        assert [int(k) for k,v in rows]==list(range(1<<bits[bap])),(bap,len(rows))
        vectors.append([[signed(v) for v in row.split()] for k,row in rows])
    section=text.split('Table E3.6 Large Mantissa Inverse Quantization (Remapping) Constants')[-1].split('3.4.5')[0]
    rows=re.findall(r'^\s*(?:(\d+)\s+)?x([≥<])0\s+((?:(?:0x[0-9a-fA-F]{4}|N/A)\s+){5}(?:0x[0-9a-fA-F]{4}|N/A))\s*$',section,re.M)
    assert len(rows)==24,len(rows)
    remap=[]
    for i in range(12):
        positive,negative=rows[2*i:2*i+2]
        assert positive[0]==str(i+8) and positive[1]=='≥' and negative[1]=='<'
        p=[0 if x=='N/A' else signed(x) for x in positive[2].split()]
        n=[0 if x=='N/A' else signed(x) for x in negative[2].split()]
        assert p[::2]==n[::2] and p[1]==n[1]==0
        if i<9:assert p[3]==16384 and p[5]==8192
        remap.append([p[0],p[2],p[4],n[3],n[5]])
    cosine=[round(math.sqrt(2)*math.cos(k*math.pi/6)*(1<<23)) for k in (1,0)]
    cosine.append(round(math.sqrt(2)*math.cos(5*math.pi/12)*(1<<23)))
    assert cosine==[10273905,11863283,3070444]
    return hebap,bits,vectors,remap,cosine


def render(hebap,bits,vectors,remap,cosine):
    output='# Numeric ATSC A/52:2018 Annex E AHT tables.\n# Generated by tests/generate-eac3-aht-tables.py; see docs/eac3.md.\n'
    for label,values in [('eac3_hebap',hebap),('eac3_aht_bits',bits)]:
        output+=label+':\n    .byte '+','.join(map(str,values))+'\n'
    output+='\n.p2align 1\neac3_aht_remap:\n'
    output+=''.join('    .short '+','.join(map(str,row))+'\n' for row in remap)
    offsets=[0]
    for rows in vectors:offsets.append(offsets[-1]+len(rows)*12)
    output+='\n.p2align 2\neac3_aht_vq_offsets:\n    .long 0,'+','.join(map(str,offsets[:-1]))+'\n'
    output+=''.join(f'.equ EAC3_AHT_COS{i}, {value}\n' for i,value in enumerate(cosine))
    output+='eac3_aht_vq:\n'
    output+=''.join('    .short '+','.join(map(str,row))+'\n' for rows in vectors for row in rows)
    return output


if __name__=='__main__':
    generated=render(*tables())
    if '--check' in sys.argv:
        if TARGET.read_text()!=generated:raise SystemExit('src/eac3_aht_tables.inc is stale')
        print('AHT numeric tables match the pinned A/52 specification')
    else:TARGET.write_text(generated)
