#!/usr/bin/env python3
"""Generate src/tags_genres.inc, the ID3v1 genre names for src/tags.s.

usage: python3 tests/generate-genre-table.py [--check]

Genres 0-79 are the ID3v1 list; 80-191 are the Winamp extensions that ID3
readers (FFmpeg among them) use, with their later spellings. ID3v2 "(N)"
genres and MP4 gnre items name them too. tests/verify-tags.py checks every
name against FFmpeg, except genre 133, which takes the current name
"Afro-Punk" in place of the original slur (FFmpeg 6.1 keeps the original).
"""
from pathlib import Path
import sys

TARGET = Path(__file__).resolve().parent.parent / 'src' / 'tags_genres.inc'

GENRES = [
    'Blues', 'Classic Rock', 'Country', 'Dance', 'Disco', 'Funk', 'Grunge', 'Hip-Hop', 'Jazz', 'Metal',
    'New Age', 'Oldies', 'Other', 'Pop', 'R&B', 'Rap', 'Reggae', 'Rock', 'Techno', 'Industrial',
    'Alternative', 'Ska', 'Death Metal', 'Pranks', 'Soundtrack', 'Euro-Techno', 'Ambient', 'Trip-Hop', 'Vocal',
    'Jazz+Funk', 'Fusion', 'Trance', 'Classical', 'Instrumental', 'Acid', 'House', 'Game', 'Sound Clip',
    'Gospel', 'Noise', 'AlternRock', 'Bass', 'Soul', 'Punk', 'Space', 'Meditative', 'Instrumental Pop',
    'Instrumental Rock', 'Ethnic', 'Gothic', 'Darkwave', 'Techno-Industrial', 'Electronic', 'Pop-Folk',
    'Eurodance', 'Dream', 'Southern Rock', 'Comedy', 'Cult', 'Gangsta', 'Top 40', 'Christian Rap', 'Pop/Funk',
    'Jungle', 'Native American', 'Cabaret', 'New Wave', 'Psychedelic', 'Rave', 'Showtunes', 'Trailer', 'Lo-Fi',
    'Tribal', 'Acid Punk', 'Acid Jazz', 'Polka', 'Retro', 'Musical', 'Rock & Roll', 'Hard Rock',
    'Folk', 'Folk-Rock', 'National Folk', 'Swing', 'Fast Fusion', 'Bebop', 'Latin', 'Revival', 'Celtic',
    'Bluegrass', 'Avantgarde', 'Gothic Rock', 'Progressive Rock', 'Psychedelic Rock', 'Symphonic Rock',
    'Slow Rock', 'Big Band', 'Chorus', 'Easy Listening', 'Acoustic', 'Humour', 'Speech', 'Chanson', 'Opera',
    'Chamber Music', 'Sonata', 'Symphony', 'Booty Bass', 'Primus', 'Porn Groove', 'Satire', 'Slow Jam', 'Club',
    'Tango', 'Samba', 'Folklore', 'Ballad', 'Power Ballad', 'Rhythmic Soul', 'Freestyle', 'Duet', 'Punk Rock',
    'Drum Solo', 'A Cappella', 'Euro-House', 'Dance Hall', 'Goa', 'Drum & Bass', 'Club-House', 'Hardcore Techno',
    'Terror', 'Indie', 'BritPop', 'Afro-Punk', 'Polsk Punk', 'Beat', 'Christian Gangsta Rap', 'Heavy Metal',
    'Black Metal', 'Crossover', 'Contemporary Christian', 'Christian Rock', 'Merengue', 'Salsa', 'Thrash Metal',
    'Anime', 'Jpop', 'Synthpop', 'Abstract', 'Art Rock', 'Baroque', 'Bhangra', 'Big Beat', 'Breakbeat',
    'Chillout', 'Downtempo', 'Dub', 'EBM', 'Eclectic', 'Electro', 'Electroclash', 'Emo', 'Experimental',
    'Garage', 'Global', 'IDM', 'Illbient', 'Industro-Goth', 'Jam Band', 'Krautrock', 'Leftfield', 'Lounge',
    'Math Rock', 'New Romantic', 'Nu-Breakz', 'Post-Punk', 'Post-Rock', 'Psytrance', 'Shoegaze', 'Space Rock',
    'Trop Rock', 'World Music', 'Neoclassical', 'Audiobook', 'Audio Theatre', 'Neue Deutsche Welle', 'Podcast',
    'Indie Rock', 'G-Funk', 'Dubstep', 'Garage Rock', 'Psybient',
]


def render():
    assert len(GENRES) == 192
    lines = ['# Generated by tests/generate-genre-table.py; do not edit.',
             '# ID3v1 genres 0-79 and the Winamp extensions 80-191.',
             f'.equ GENRE_COUNT, {len(GENRES)}', '.p2align 1', 'genre_offsets:']
    offsets, total = [], 0
    for name in GENRES:
        offsets.append(total)
        total += len(name.encode('ascii'))
    offsets.append(total)
    for i in range(0, len(offsets), 12):
        lines.append('    .short ' + ', '.join(str(v) for v in offsets[i:i + 12]))
    lines.append('genre_names:')
    for name in GENRES:
        lines.append('    .ascii "' + name + '"')
    return '\n'.join(lines) + '\n'


def main():
    text = render()
    if '--check' in sys.argv[1:]:
        if TARGET.read_text() != text:
            raise SystemExit('src/tags_genres.inc differs from tests/generate-genre-table.py')
        print('src/tags_genres.inc matches its list')
        return
    TARGET.write_text(text)
    print(f'wrote {TARGET}')


if __name__ == '__main__':
    main()
